### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by lriaudel** [camunda/camunda-dmn-xlsx#38] opened 2021-01-13 17:02 UTC
Hi, I test with a simple xlsx like that : 
![image](https://user-images.githubusercontent.com/4172532/104483970-02481d00-55c9-11eb-80da-19a147f4637c.png)

And here the result :  
![image](https://user-images.githubusercontent.com/4172532/104484042-13912980-55c9-11eb-9b2c-c4099964dd14.png)

I use jdk11.0.3_7

**Comment by falko** [comment] 2021-01-13 23:16
Duplicate of #37

**Closed by falko** 2021-01-13 23:16 UTC
