### ISSUE TITLE
dmn-xlsx-cli-0.3.0.jar - exception

### ISSUE THREAD

**Issue by arturspiewak** [camunda/camunda-dmn-xlsx#32] opened 2020-07-22 19:49 UTC
Hi guys,
File: dmn-xlsx-cli-0.3.0.jar

Error:
MacBook-Pro-Artur-2:Downloads arti$ sudo java -jar dmn-xlsx-cli-0.3.0.jar --inputs A,B --outputs C test1.xlsx test1.dmn
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.camunda.bpm.dmn.xlsx.XlsxConverter.convert(XlsxConverter.java:38)
	at org.camunda.bpm.dmn.xlsx.cli.CommandLineConverter.main(CommandLineConverter.java:87)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more

java version:
MacBook-Pro-Artur-2:Downloads arti$ java --version
java 12.0.2 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

test1.xls from repo: https://github.com/camunda/camunda-dmn-xlsx/blob/master/xlsx-dmn-converter/src/test/resources/test1.xlsx

Anyone could help?

**Comment by falko** [comment] 2021-01-13 23:24
Duplicate of #37

**Closed by falko** 2021-01-13 23:24 UTC
